import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";

import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import Sidebar from "@/components/admin/Sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex">
        <ToastContainer
          position="top-right"
          autoClose={2000} // faster: 2 seconds instead of 5
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={true} // allows closing on click
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
          icon={true} // shows default icons
        />

        <Sidebar />

        <div className="flex-1">
          <div className="flex-1 p-2 h-18 bg-pink-600">Header</div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
