import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/user/Header";
import Footer from "@/components/user/Footer";
import ReduxProvide from "@/redux/ReduxProvider";
import ReduxProvider from "@/redux/ReduxProvider";
import { getMe } from "@/API/serverAPI";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const userRes = await getMe()
  const user = userRes.user

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <Header user={user} />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
