import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import Header from "@/components/user/Header";
import Footer from "@/components/user/Footer";
import StoreSideSection from "@/components/user/Store/StoreSideSection";
import { BreadcrumbBar } from "@/components/user/Store/BreadCrumps";
import { ShopHero } from "@/components/user/Store/ShopHero";
import PopularCategories from "@/components/user/Store/PopularCategory";
import SortFilter from "@/components/user/Store/SortFilter";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div className="min-h-full flex flex-col">
            <div className='w-full mx-auto px-8'>
                <div className="py-5 space-y-4">
                    <BreadcrumbBar />
                    <ShopHero />
                </div>
                <div className='mb-10'>
                    <PopularCategories />
                </div>

                <div className="flex gap-8 items-start">
                    <div className="w-[280px] shrink-0">
                        <StoreSideSection />
                    </div>

                    <main className="flex-1 space-y-6 min-w-0">
                        <SortFilter />
                        {children}
                    </main>
                </div>
            </div>
        </div>
    );
}
