import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import Header from "@/components/user/Header";
import Footer from "@/components/user/Footer";
import StoreSideSection from "@/components/user/Store/StoreSideSection";
import { BreadcrumbBar } from "@/components/user/Store/BreadCrumps";
import { ShopHero } from "@/components/user/Store/ShopHero";
import PopularCategories from "@/components/user/Store/PopularCategory";
import SortFilter from "@/components/user/Store/SortFilter";
import FilterDrawer from "@/components/user/Store/FilterDrawer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div className="min-h-full flex flex-col">
            {/* container-app centers content up to 1400px, scales for 3xl/4xl via CSS */}
            <div className="container-app">
                <div className="py-4 sm:py-5 space-y-4">
                    <BreadcrumbBar />
                    <ShopHero />
                </div>
                <div className="mb-6 sm:mb-8 overflow-x-auto scrollbar-hide">
                    <PopularCategories />
                </div>

                <div className="flex gap-6 lg:gap-8 items-start">
                    {/* Sidebar — visible lg+ */}
                    <div className="hidden lg:block w-[240px] xl:w-[260px] 2xl:w-[280px] shrink-0 sticky top-24">
                        <StoreSideSection />
                    </div>
                    <main className="flex-1 min-w-0 w-full space-y-5">
                        <SortFilter filterDrawer={
                            <FilterDrawer>
                                <StoreSideSection />
                            </FilterDrawer>
                        } />
                        {children}
                    </main>
                </div>
            </div>
        </div>
    );
}
